steps:
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  args:
  - gcloud
  - functions
  - deploy
  - cloud-build-demo
  - --region=asia-east1
  - --source=.
  - --trigger-http
  - --runtime=python39
