# api-deploy.cloudbuild.yaml contents

steps:
  # Print the full Pub/Sub message for debugging
  - id: "Echo Pub/Sub message"   
    name: gcr.io/cloud-builders/gcloud
    entrypoint: /bin/bash
    args:
      - '-c'
      - |
        echo ${_BODY}

  # Print the full Pub/Sub message for debugging
  - id: "Echo Pub/Sub message"
    name: gcr.io/cloud-builders/gcloud
    entrypoint: /bin/bash
    args:
      - '-c'
      - |
        echo "Pub/Sub Message: ${_BODY}" | jq .
        
  # Use jq to parse Pub/Sub message JSON
  - id: "Parse Pub/Sub Message"
    name: gcr.io/cloud-builders/gcloud
    entrypoint: /bin/bash
    args:
      - '-c'
      - |
        # Parse JSON using jq or You can search the _SUBSTITION
        ACTION=$(echo ${_BODY} | jq -r '.message.data.action')
        RESOURCE=$(echo ${_BODY} | jq -r '.message.data.tag')
        
        # Check if conditions are met
        if [[ "${ACTION}" == "INSERT" && "${RESOURCE}" == "asia-east1-docker.pkg.dev/esun-cncf/epic-quest/server-side" ]]; then
          echo "Conditions met. Deploying to Cloud Run."
          # Add your deploy command here
        else
          echo "Conditions not met. Skipping deployment."
        fi       

  # Cloud Run Deploy
  - id: "Deploy to Cloud Run"
    name: gcr.io/cloud-builders/gcloud
    args:
      - run
      - deploy
      - ${_SERVICE}
      - --image=${_IMAGE_NAME}
      - --region=${_REGION}
      - --revision-suffix=${_REVISION}
      - --project=${PROJECT_ID}
      - --allow-unauthenticated
      - --tag=${_IMAGE_TAG}


# 專案資訊
substitutions:
  _SERVICE: epic-quest


options:
  # machineType: N1_HIGHCPU_8  # 设置机器类型
  substitution_option: ALLOW_LOOSE
  logging: CLOUD_LOGGING_ONLY      